#!/bin/bash

export RTL_TOP=pe
export DOCKER_NAME=compile

echo "Creating compile container"
docker run -w $REPOROOT -i -t -d -v $REPOROOT:$REPOROOT --name=$DOCKER_NAME $DOCKERTAG > /dev/null
echo "Compiling verilog"
compile_cmd="verilator -Wall -y ./src --cc pe -f $REPOROOT/tools/conf/incdir.f --exe $TBROOT/${RTL_TOP}_tb/$RTL_TOP.cpp"
echo $compile_cmd
docker exec -t -w $REPOROOT $DOCKER_NAME bash -c "$compile_cmd"
echo "Compiling C"
compile_cmd="make -j -C obj_dir -f V$RTL_TOP.mk V$RTL_TOP"
echo $compile_cmd
docker exec -t -w $REPOROOT $DOCKER_NAME bash -c "$compile_cmd"
echo "Removing container"
docker stop $DOCKER_NAME > /dev/null
docker rm $DOCKER_NAME > /dev/null

