#!/bin/bash

export RTL_TOP=pe
export DOCKER_NAME=compile

export EXTRA_VERLIATOR_ARGS
export CFLAGS;

while [ $# -ne 0 ]
do
    arg="$1"
    case "$arg" in
        -top)
            RTL_TOP=$2
            CFLAGS+=\ -DCXX_TOP_LEVEL=V$2
            shift
            ;;
        -trace)
            EXTRA_VERILATOR_ARGS+=--trace-fst
            CFLAGS+=\ -DTRACE
            ;;
    esac
    shift
done

export TARGET_PATH=$TBROOT/$RTL_TOP/build

echo "RTL_TOP: $RTL_TOP"

echo "Cleaning last build"
rm -rf $TARGET_PATH
echo "Creating compile container"
docker run -w $REPOROOT -i -t -d -v $REPOROOT:$REPOROOT --name=$DOCKER_NAME $DOCKERTAG > /dev/null
echo "Compiling verilog"
compile_cmd="verilator -Wall $EXTRA_VERILATOR_ARGS --Mdir $TARGET_PATH -CFLAGS \"$CFLAGS\" --cc $RTL_TOP -f $REPOROOT/tools/conf/incdir.f -y $TBROOT/$RTL_TOP --exe $REPOROOT/tools/csrc/main.cpp"
echo $compile_cmd
docker exec -t -w $REPOROOT $DOCKER_NAME bash -c "$compile_cmd"
echo "Compiling C"
compile_cmd="OPT=-DVL_DEBUG make -j -C $TARGET_PATH -f V$RTL_TOP.mk V$RTL_TOP"
echo $compile_cmd
docker exec -t -w $REPOROOT $DOCKER_NAME bash -c "$compile_cmd"
echo "Removing container"
docker stop $DOCKER_NAME > /dev/null
docker rm $DOCKER_NAME > /dev/null

