#!/bin/bash

export DOCKER_NAME=run

echo "Creating run container"
docker run -w $REPOROOT -i -t -d -v $REPOROOT:$REPOROOT --name=$DOCKER_NAME $DOCKERTAG > /dev/null
echo "Running Verilog"
run_cmd="$REPOROOT/obj_dir/$*"
echo $run_cmd
docker exec -t -w $REPOROOT $DOCKER_NAME bash -c "$run_cmd"
echo "Removing container"
docker stop $DOCKER_NAME > /dev/null
docker rm $DOCKER_NAME > /dev/null

